version: "3.1"

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:14.7
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=marushop
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # express-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - .:/usr/src/app
  #   depends_on:
  #     - postgres
